### ISSUE TITLE
Error on running "python main.py" command 

### ISSUE THREAD

**Issue by RangerCoder99** [OtchereDev/coursehunter-video-downloader#3]
Getting this error on Windows 10 with Python 3.8.5

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from module.extractor import extract_video, extract_video_url
  File "D:\PROJECTS\TOOLS\coursehunter-video-downloader\module\extractor\extract_video_url.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "C:\Python38\lib\site-p
![error](https://user-images.githubusercontent.com/22674459/92754942-beff4880-f361-11ea-9bc6-4b01d7f76264.png)
ackages\robobrowser\__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "C:\Python38\lib\site-packages\robobrowser\browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (C:\Python38\lib\site-packages\werkzeug\__init__.py)`

**Comment by RangerCoder99** [comment]
![error](https://user-images.githubusercontent.com/22674459/92755166-f241d780-f361-11ea-8aa2-24b5a1a424a8.png)

**Comment by OtchereDev** [comment]
I am very sorry the issue you encountering @RangerCoder99 really i dont know what is going from with your python but i have some research on stackoverflow for you and i have three solution, so try any one of them and let see which one works:

Solution_1. edit file "extract_video_url.py" in extractor folder in the module folder by prefixing:
`import werkzeug`
`werkzeug.cached_property = werkzeug.utils.cached_property`
on the first two line of code

Solution_2. Or you can downgrade Werkzung with these :
`
pip install --upgrade Werkzeug==0.16.0`

Solution_3. Or you can use python 3.7 version to run the app 

I hope this helps, please comment below which one work so that the community will benefit also. Thank you

**Comment by RangerCoder99** [comment]
I tried option 2 and it's working now! Thanks for doing all the research!
